# Generated by Django 4.2.7 on 2023-11-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_in_stock_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant_title',
            field=models.CharField(default='color/size', max_length=255),
            preserve_default=False,
        ),
    ]
