# Generated by Django 4.2.7 on 2023-11-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productvariant_in_stock_productvariant_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='variant_title',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.FloatField(),
        ),
    ]
